default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: bike-alerts_development
  username:
  password:

test:
  <<: *default
  database: bike-alerts_test

production:
  <<: *default
  database: bike-alerts_production
  username: bike-alerts
  password: <%= ENV['BIKE-ALERTS_DATABASE_PASSWORD'] %>
